from setuptools import setup, find_packages

setup(
    name='climasmart',
    version='0.1.2',
    description='ClimaSmart: A Climate Monitoring Toolkit with SPI, SPEI, VCI, LSTM Forecasting, and GEE Support',
    author='Tadele Melese',
    author_email='tadelemelese21m@gmail.com',
    url='https://github.com/tadele-melese/ClimaSmart',
    packages=find_packages(),
    install_requires=[
        'numpy>=1.21.0',
        'pandas>=1.3.0',
        'scikit-learn>=1.0',
        'matplotlib>=3.4.0',
        'seaborn>=0.11.0',
        'scipy>=1.7.0',
        'tensorflow>=2.8.0',
        'streamlit>=1.10.0',
        'geemap>=0.10.0',
        'earthengine-api>=0.1.355',
        'xarray',
        'rasterio>=1.2.0',
        'statsmodels>=0.13.0',
        'geopandas>=0.12.0',
        'shapely>=2.0.0',
        'pymannkendall>=1.4.1',
        'torch>=1.13.0',
        'shap>=0.41.0',
        'tqdm>=4.62.3',
        'folium>=0.14.0',
        'ipyleaflet>=0.17.0',
        'dask>=2022.2.0',
    ],
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'Topic :: Scientific/Engineering :: Atmospheric Science',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
    ],
    python_requires='>=3.8',
)
